### ISSUE TITLE
tfuser: live command panics

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/tfexplorer#53]
```
▶ tfuser --seed seed.devnet live --end 5000 
ID: 61 Expires: 13-Apr-2021 11:36:40
null
panic: nil map

goroutine 1 [running]:
main.printResult.func2(0xc0007c2800, 0x7, 0x8, 0xc000397648, 0xc0007e02d8, 0x2)
	/home/zaibon/dev/go/src/github.com/threefoldtech/tfexplorer/cmds/tfuser/cmds_live.go:80 +0x440
main.printResult(0x3d, 0xc00075a000, 0x303d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1b35b78, 0x0, ...)
	/home/zaibon/dev/go/src/github.com/threefoldtech/tfexplorer/cmds/tfuser/cmds_live.go:93 +0x6ac
main.cmdsLive(0xc0001b22c0, 0x0, 0xc0003ce1c0)
	/home/zaibon/dev/go/src/github.com/threefoldtech/tfexplorer/cmds/tfuser/cmds_live.go:36 +0x2b2
github.com/urfave/cli.HandleAction(0x11666e0, 0x130fc00, 0xc0001b22c0, 0xc0001b22c0, 0x0)
	/home/zaibon/dev/go/pkg/mod/github.com/urfave/cli@v1.22.3/app.go:526 +0x11a
github.com/urfave/cli.Command.Run(0x12a2d49, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12d41f1, 0x32, 0x0, ...)
	/home/zaibon/dev/go/pkg/mod/github.com/urfave/cli@v1.22.3/command.go:174 +0x56e
github.com/urfave/cli.(*App).Run(0xc0000a8000, 0xc0000321e0, 0x6, 0x6, 0x0, 0x0)
	/home/zaibon/dev/go/pkg/mod/github.com/urfave/cli@v1.22.3/app.go:279 +0x7bb
main.main()
	/home/zaibon/dev/go/src/github.com/threefoldtech/tfexplorer/cmds/tfuser/main.go:528 +0x36b0
```

**Comment by DylanVerstraete** [comment]
Are you sure you are using the latest built binary? I cannot reproduce:

```
➜  tfuser git:(master) ✗ ./tfuser --seed user.seed --bcdb http://192.168.0.170:8080/explorer live --start 9180 --end 9200
ID: 9181 Expires: 06-May-2020 09:38:25
Workload 0:
  kind: volume
  results:
  - node: 2CBouXMr24TfNxxTs2i4ZqHgbpEagV1c14BnnjrZYdr7
    state: ok
    volume_id: 9181-0
  size: 1
  type: SSD
-------------------------
ID: 9182 Expires: 06-May-2020 09:49:53
Workload 0:
  kind: volume
  results:
  - node: 2CBouXMr24TfNxxTs2i4ZqHgbpEagV1c14BnnjrZYdr7
    state: ok
    volume_id: 9182-0
  size: 1
  type: SSD
-------------------------

```
